1801|I know [Powershell is keen on putting UTF BOMs in everything](http://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom).
1802|Yeah, the written file is Unicode. The storage.json needs to be an ANSI encoded file?
1803|"I fixed most of the issues: If there is an error in your promise, the picker will hide and you have a chance to handle the error from the returned promise from the pick() call.  @jrieken is our proxy from main to PH not handling errors? I have the following extension that shows a pick with error but in the console I still get an error about unhandled promise:  ``` typescript export function activate(context: vscode.ExtensionContext) {      var disposable = vscode.commands.registerCommand('extension.sayHello', () => {         vscode.window.showQuickPick(new Promise((c, e) => {             setTimeout(() => {                 e(new Error(""does not work""));             }, 2000);         })).then(null, (e) => {             vscode.window.showErrorMessage(e.toString());         });     });      context.subscriptions.push(disposable); } ```  ![image](https://cloud.githubusercontent.com/assets/900690/11418595/91155dd2-9421-11e5-9ae7-d5295da015a2.png)"
1804|async / await is ES7 not ES6 feature. But I agree we need Intelisence on them,
1805|@Tyriar **outside `<?php` tags** means what? Are they availabe when outside `<?php ?>` tags in PHP files?
1806|Thanks for the quick fix!
1807|Duplicate https://github.com/Microsoft/vscode/issues/239
1808|Outside `<?php ?>` is HTML, inside is PHP. So the HTML auto complete should only be available outside the `<?php ?>` tags.
1809|:heavy_check_mark:
1810|Yes, that is intentional. Because multiple providers can contribute to a result, like multiple document symbol provider, failure of one shouldn't let all fail. That also applies to the case of just 1 provider...
1811|[A JSON document must be Unicode encoded always. But it does not support BOM.](http://tools.ietf.org/html/rfc4627#section-3)
1812|@Tyriar But now they are not available outside the `<?php ?>` tags in `.php` files, maybe they are only available in `.html` files.
1813|@bpasero I don't see `setInterval` in your code.  @alexandrudima I think this is a duplicate of the editor change event firing to often
1814|"By the way I just updated to version 0.10.2 but the issue remains. But from now on I will most likely rely on that version, if no other instructions are given.  @bpasero I'll try the build and run from source at the weekend. (If needed) The Reload Window option is also slow, cpu consuming and causes the ""does not respond"" error message. Here's the Profile dump: **EDIT**: Removed because it may contained user data  And some picture:  ![vscode4](https://cloud.githubusercontent.com/assets/7961978/11419137/aec7c230-9425-11e5-97b1-8f441068d6b7.PNG)"
1815|That's because we use the `Thenable` as the common denominator of promise-wannabes. The VS Code api will accept anything that is like a promise to make it easy to integrate existing code.   Promises that are _returned_ from the API are WinJS-promises (which btw don't support catch). We didn't declare that in the API since we will likely adopt native promises some time.
1816|Please verify that this isn't the same issue as #94.  If it isn't then please attach the file so that we can reproduce.
1817|Thanks @SamVerschueren
1818|The only explanation for this that I can find is #696. Closing this as a dupe of that and let's see if they keep on coming.
1819|It is, by just setting a different selection array  Remove the first selection:  ``` var textEditor = vscode.window.activeTextEditor; var selections = textEditor.selections;  textEditor.selections = selections.slice(1); ```
1820|"Starting Code with ""NODE_TLS_REJECT_UNAUTHORIZED=0"" seems to ""fix"" some issues and I actually get a list of extensions, but I still cannot install the extensions themselves. I get timeouts in the dev console after a while and that's it."
1821|This is cool.
1822|Yeah, we never got around doing that...
1823|@alexandrudima pretty please ;-)
1824|Can you provide the whole code please, also what line you edit, and whether this is a ts or js file?
1825|This doesn't seem to be an inherent issue with Code. But I'm glad people are finding solutions.
1826|It actually is hard coded to 100
1827|If you are going to adopt native promises, why are WinJS-promises used then? Native promises support catch which means the API will change when native promises are being adopted. Isn't it better to use a decent polyfill/ponyfill for now instead of the microsoft implementation?  Just wondering :).
1828|We plan to improve this by integrating the Salsa work from the TypeScript team: Microsoft/TypeScript#4789
1829|@jrieken https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/utils.ts#L52
1830|Our project started a little before the general availability of the native promises ;-) Also, the editor widget must still support environments without the native promise.
1831|"@wUFr another thought I had was if - once VS Code is up and running - you could see if reloading the application is also slow. For that you can just trigger View | Command Palette | Reload Window.  If that action turns out to be as slow, we have a chance to run a profiler to see where the time is spent. For that - before reloading - run Help | Toggle Developer Tools, click Profiles, then press the Start button and run the reload action. After that, press the Stop button. You should get a list of function calls and their timings. You can export this report from the little ""Save"" button next to ""Profile 1"" on the left.  ![image](https://cloud.githubusercontent.com/assets/900690/11419786/f416ec72-9429-11e5-8f5c-b4267c954076.png)"
1832|I'm doing some more investigation on this to see if I can unblock myself by getting an `ia32` version of the module loaded, so I installed the `x86` version of node.js, installed the native module (which in turned got the right binary).  Now I get the following error:  ![native-module-error](https://cloud.githubusercontent.com/assets/434140/11419783/c1696724-947d-11e5-8d1e-bd5d4e564ff5.png)  Are native modules not supported in extensions?
1833|**The good:** Nothing really. **The bad:** Code extensions unfortunately don't support native extensions. **The ugly:** There is a workaround. Bear with me: - Your native packages must be compiled against the exact same version of node and v8 that Code is. [Specifically](https://github.com/Microsoft/vscode/blob/master/scripts/npm.sh):   - `npm_config_disturl=https://atom.io/download/atom-shell`   - `npm_config_target=` whatever value is there on [`electronVersion`](https://github.com/Microsoft/vscode/blob/master/package.json)   - `npm_config_arch=` whatever the bit architecture you need   - `HOME=` something other that `~`, like `~/.electron-gyp`, so node-gyp and npm don't confuse themselves. - The extension package must contain the binaries for _all_ platforms Code supports: `win32-ia32`, `darwin`, `linux-ia32` and `linux-x64`. It would then dynamically require the correct binary for the running platform at runtime. [bindings](https://www.npmjs.com/package/bindings) might help you there.
1834|That's why a ponyfill comes in handy :). It uses the native promises if they are available, if not it will use the polyfill.   Example: [pinkie-promise](https://github.com/floatdrop/pinkie-promise)
1835|Duplicate of #347
1836|It's running as a git pre-commit hook now.
1837|Thanks @joaomoreno for report duplication  I would like to suggest that VSCode should just look at .vscode/extensions folder of the opened folder to read extension in addition to global .vscode/extensions
1838|@bpasero  worked .. thx
1839|"Yeah I just came across [this walkthrough](https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md) which somewhat outlines the ""ugly"" side of things :stuck_out_tongue:.  Native modules are a pain, but I might keep at it and see where I can get to (or see if the native module can be reimplemented in ""plain ol' JavaScript"", but somehow I don't expect it to be possible."
1840|Thanks, I assumed it was readonly.
1841|Here is the VSCode logs after running it in verbose mode and opening a sass file in the editor : ![capture1](https://cloud.githubusercontent.com/assets/15893458/11420336/b930cc1e-942d-11e5-84af-27875f0a7723.PNG)  At the same time, I started the watch gulp task : ![capture2](https://cloud.githubusercontent.com/assets/15893458/11420374/0163d6d4-942e-11e5-899c-ed393d4bfb56.PNG)
1842|"I just reproduced it again. Made a new directory, and moved a file into it. Everything gets the red underline and the warning ""This can only be used with ES6. Make sure to have a jsconfig.json-file which sets the target to ES6"".  Restart VSCODE and it goes away."
1843|I have the same problem except while restarting normally fixes this, in this case it's still no working after a restart for a file called schema.js
1844|Perhaps the best practice is to add version information into the name of setup, e.g. `VScode-0.10.2.exe`.
1845|This is #335
1846|This is #335
1847|This is likely #335
1848|Great :+1:
1849|@fouckybzh do you have any extensions installed?
1850|"@maritz What do you mean by ""Starting Code with""? You put that into the settings?"
1851|Thank you!!
1852|I improved the error message for now so next time we now what is wrong with the passed uri. The error might be comming from debug backend.
1853|@joaomoreno @weinand I'm not familiar at all with system-wide find/replace mechanics on OS X.  Is the text to find going to some system specific location? (is it like a clipboard mechanism?) Can this be accessed from electron?
1854|@weinand this is as designed, right? Do you think there is something better we could do here?
1855|**Disclmaimer**: This is not safe! (as is strict-ssl: false)  That's an environment variable. So in linux when starting vscode from command line you'd do this:  ``` NODE_TLS_REJECT_UNAUTHORIZED=0 ./Code ```
1856|Thanks it works if I use `Set-Content` (which encodes it in Ascii) instead of `Out-File`.
1857|This can get really ugly for more complex cases. (Logic mostly omitted.)  Highlighting works fine again after removing the middle parameter of the `for` cycle.   ![vs-highlight-error2](https://cloud.githubusercontent.com/assets/3373181/11422134/e370a0e2-9439-11e5-8d0c-c64350df5918.png)
1858|While on vscode on view you need to click on show output and then select omnisharp server
1859|"In the future we will make the `""request""` field required so that warning is correct. Using `""request""` we distinguish if we should launch or attach.  As for the type not being an accepted value I made a PR in your repo to fix that."
1860|Fully agree - everyone would like to have it but the adoption will be laborious esp that we build on `done` and `cancel` from WinJS...
1861|Please reopen if you see it again with data from the console output.
1862|In general readonly properties have the `@readonly` jsdoc tag
1863|@bpasero will know but I believe the zoom states are given by electron/chromium and that there is no 1.5 level
1864|"@Morgy93 thanks a lot for the profile, this helped identify the issue and in fact many more users are hit. This likely qualifies for an update that we will push out to all users but we need some verification first. So I have a couple of asks for you:  1.) can you download the following build of VS Code (standalone zip, no installer) and open Code.exe to see if performance is better. I uploaded the zip to my onedrive: http://1drv.ms/1NQvCOu  2.) if performance is better: close the instance and open `\resources\app\out\vs\workbench\electron-browser\index.html` in that zip and make the following console.log additions after this line:  ``` javascript process.env['VSCODE_SHARED_IPC_HOOK'] = configuration.sharedIPCHandle;  console.log('URL length: ' + window.document.URL.length); console.log(JSON.stringify(configuration, null, '\t')); ```  Then save the file and run Code again from the zip and hit Help | Toggle Developer Tools. You should then see potentially lots of output from the log statements. I would need the entire log, since it may contain user data it should probably be not attached to this issue but you can send it via mail (benjpas@microsoft.com)."
1865|OK, messing with this a little more I came across that highlighting breaks if there is a `variableName<` text in the middle parameter of `for`. I think it's something with the parsing of templates.  - Not happens if there is whitespace, e.g. `variableName <` - Not happens for `funcCall(variable)<` - Not the `<` operator triggers the error, `variableName<<` also works  Also the consequences are not affecting only to the `for` body, although they are more limited afterwards.   ![vs-highlight-error3](https://cloud.githubusercontent.com/assets/3373181/11422480/9959a47e-943c-11e5-809a-c7a322ef188b.png)
1866|"I've analysed the problem and found this:  The source maps in our extensions 'out' folder have broken paths in their ""sources"" array. Normally these path entries should point to the source relative from the sourcemap location. But for the Monaco workspace these paths are relative to some other location. This makes it difficult for node-debug to figure out where the source lives. I can add more ""guessing"" heuristics to node-debug, but I think we should fix the root of the problem as well.  Here is an example from the typescript extension's ""bufferSyncSupport"":  - source: vscode/extensions/typescript/**src**/features/bufferSyncSupport.ts - dest: vscode/extensions/typescript/**out**/features/bufferSyncSupport.js  Since the sourcemap lives next to the destination file, the minimal relative path between map and source is ""../../src/features/bufferSyncSupport.js"".  However the actual path in the sources array is ""../../vscode/extensions/typescript/src/features/bufferSyncSupport.ts"".  If I run tsc in the typescript extension folder manually, the path in the source map is correct. Only the build watcher creates a broken path.  @joaomoreno, could it be that some gulp script is massaging the paths in the source maps?"
1867|Ok. Got it :)  Here is the log you need:  ``` [INFO] Starting OmniSharp at '/home/injac/aspnet/WebApiTest'... [INFO] Started OmniSharp from '/home/injac/bin/vscode/resources/app/extensions/csharp-o/bin/omnisharp' with process id 1344... [INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/home/injac/aspnet/WebApiTest' on host 1301. [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/home/injac/aspnet/WebApiTest/project.json'. [INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/home/injac/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-rc1-final'. [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/home/injac/aspnet/WebApiTest' for DNX projects [INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Using '/home/injac/.dnx/runtimes/dnx-mono.1.0.0-rc1-final' for design time host. [ERROR:OmniSharp.Startup] The project system 'DnxProjectSystem' threw an exception. System.InvalidOperationException: File name has not been set   at System.Diagnostics.Process.Start_common (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) <0x420fac50 + 0x0011b> in <filename unknown>:0    at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo) <0x420fa8c0 + 0x0005b> in <filename unknown>:0    at OmniSharp.Dnx.DesignTimeHostManager.Start (System.String hostId, System.Action`1 onConnected) <0x420c2000 + 0x0096b> in <filename unknown>:0    at OmniSharp.Dnx.DnxProjectSystem.Initalize () <0x420bf270 + 0x0025f> in <filename unknown>:0    at OmniSharp.Startup.Configure (IApplicationBuilder app, ILoggerFactory loggerFactory, IOmnisharpEnvironment env, ISharedTextWriter writer) <0x42075580 + 0x003d9> in <filename unknown>:0  [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/home/injac/aspnet/WebApiTest' [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/home/injac/aspnet/WebApiTest'. [INFORMATION:OmniSharp.Startup] Solution has finished loading [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files ```  It looks like the mono-runtime is required for omni-sharp.
1868|Why is this closed? This is still a valid issue that needs to be fixed sometime
1869|No extension has been installed. To be safe, I uninstalled and reinstalled VSCode but I still have the same behavior. I just did a test on another machine with a fresh install of vscode (0.10.2) .... same problem :(
1870|which version of mono do you have?, not the runtime, mono compiler
1871|I installed the latest mono 4.2.1 from the xamarin-servers.
1872|https://visualstudio.uservoice.com/forums/293070-visual-studio-code
1873|@bpasero Performance is good again - log sent via mail.
1874|It works (Intellisense) after installing the mono-runtime using dnvm. This should be mentioned within the Linux documentation.  But there are additional errors now in the omnisharp-log:  ``` [INFO] Starting OmniSharp at '/home/injac/aspnet/WebApiTest'... [INFO] Started OmniSharp from '/home/injac/bin/vscode/resources/app/extensions/csharp-o/bin/omnisharp' with process id 1805... [INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location '/home/injac/aspnet/WebApiTest' on host 1761. [INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime '/home/injac/.dnx/runtimes/dnx-mono.1.0.0-rc1-final'. [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Found project '/home/injac/aspnet/WebApiTest/project.json'. [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning '/home/injac/aspnet/WebApiTest' for DNX projects Process ID 1826 Listening on port 52106 [INFORMATION:OmniSharp.Dnx.DesignTimeHostManager] Running DesignTimeHost on port 52106, with PID 1826 Client accepted 127.0.0.1:52106 [INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Connected Client accepted 127.0.0.1:52106 [INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] No solution files found in '/home/injac/aspnet/WebApiTest' [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in '/home/injac/aspnet/WebApiTest'. [INFORMATION:OmniSharp.Startup] Solution has finished loading [INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files [ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Diagnostic must have span '[657..657)' Parameter name: diagnostics System.ArgumentException: Diagnostic must have span '[657..657)' Parameter name: diagnostics   at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext.VerifyDiagnosticsArgument (ImmutableArray`1 diagnostics, TextSpan span) <0x40677000 + 0x0037b> in <filename unknown>:0    at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext..ctor (Microsoft.CodeAnalysis.Document document, TextSpan span, ImmutableArray`1 diagnostics, System.Action`2 registerCodeFix, Boolean verifyArguments, CancellationToken cancellationToken) <0x40676db0 + 0x0004f> in <filename unknown>:0    at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext..ctor (Microsoft.CodeAnalysis.Document document, TextSpan span, ImmutableArray`1 diagnostics, System.Action`2 registerCodeFix, CancellationToken cancellationToken) <0x40676d60 + 0x0003b> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetCodeFixContext>d__9.MoveNext () <0x40675fa0 + 0x007eb> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40677db0 + 0x0001f> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetActions>d__7.MoveNext () <0x40672430 + 0x0061e> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetCodeActions>d__5.MoveNext () <0x40671b60 + 0x00166> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<CastToObject>d__8`1[T].MoveNext () <0x4039f2f0 + 0x0019b> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<ExecuteAsync>d__3.MoveNext () <0x40356dc0 + 0x0030b> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<ExecuteAsync>d__2.MoveNext () <0x40356510 + 0x0018a> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.ControllerActionInvoker+<InvokeActionAsync>d__7.MoveNext () <0x40355510 + 0x001da> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeActionFilterAsync>d__41.MoveNext () <0x403520e0 + 0x00cf4> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeAsync>d__32.MoveNext () <0x4032b510 + 0x0082d> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.MvcRouteHandler+<InvokeActionAsync>d__3.MoveNext () <0x403222f0 + 0x0036c> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.MvcRouteHandler+<RouteAsync>d__2.MoveNext () <0x4031a000 + 0x006f0> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Routing.Template.TemplateRoute+<RouteAsync>d__25.MoveNext () <0x40317fe0 + 0x007c8> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute+<RouteAsync>d__10.MoveNext () <0x403174a0 + 0x003d5> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Routing.RouteCollection+<RouteAsync>d__10.MoveNext () <0x403163a0 + 0x003b7> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () <0x403153b0 + 0x00311> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware+<Invoke>d__4.MoveNext () <0x40314110 + 0x003d6> in <filename unknown>:0  [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 404 22ms [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 360ms [ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Diagnostic must have span '[663..663)' Parameter name: diagnostics System.ArgumentException: Diagnostic must have span '[663..663)' Parameter name: diagnostics   at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext.VerifyDiagnosticsArgument (ImmutableArray`1 diagnostics, TextSpan span) <0x40677000 + 0x0037b> in <filename unknown>:0    at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext..ctor (Microsoft.CodeAnalysis.Document document, TextSpan span, ImmutableArray`1 diagnostics, System.Action`2 registerCodeFix, Boolean verifyArguments, CancellationToken cancellationToken) <0x40676db0 + 0x0004f> in <filename unknown>:0    at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext..ctor (Microsoft.CodeAnalysis.Document document, TextSpan span, ImmutableArray`1 diagnostics, System.Action`2 registerCodeFix, CancellationToken cancellationToken) <0x40676d60 + 0x0003b> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetCodeFixContext>d__9.MoveNext () <0x40675fa0 + 0x007eb> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40677db0 + 0x0001f> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetActions>d__7.MoveNext () <0x40672430 + 0x0061e> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetCodeActions>d__5.MoveNext () <0x40671b60 + 0x00166> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<CastToObject>d__8`1[T].MoveNext () <0x4039f2f0 + 0x0019b> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<ExecuteAsync>d__3.MoveNext () <0x40356dc0 + 0x0030b> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<ExecuteAsync>d__2.MoveNext () <0x40356510 + 0x0018a> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.ControllerActionInvoker+<InvokeActionAsync>d__7.MoveNext () <0x40355510 + 0x001da> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeActionFilterAsync>d__41.MoveNext () <0x403520e0 + 0x00cf4> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeAsync>d__32.MoveNext () <0x4032b510 + 0x0082d> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.MvcRouteHandler+<InvokeActionAsync>d__3.MoveNext () <0x403222f0 + 0x0036c> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.MvcRouteHandler+<RouteAsync>d__2.MoveNext () <0x4031a000 + 0x006f0> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Routing.Template.TemplateRoute+<RouteAsync>d__25.MoveNext () <0x40317fe0 + 0x007c8> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute+<RouteAsync>d__10.MoveNext () <0x403174a0 + 0x003d5> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Routing.RouteCollection+<RouteAsync>d__10.MoveNext () <0x403163a0 + 0x003b7> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () <0x403153b0 + 0x00311> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware+<Invoke>d__4.MoveNext () <0x40314110 + 0x003d6> in <filename unknown>:0  [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 404 18ms [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 20ms [ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: Diagnostic must have span '[666..666)' Parameter name: diagnostics System.ArgumentException: Diagnostic must have span '[666..666)' Parameter name: diagnostics   at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext.VerifyDiagnosticsArgument (ImmutableArray`1 diagnostics, TextSpan span) <0x40677000 + 0x0037b> in <filename unknown>:0    at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext..ctor (Microsoft.CodeAnalysis.Document document, TextSpan span, ImmutableArray`1 diagnostics, System.Action`2 registerCodeFix, Boolean verifyArguments, CancellationToken cancellationToken) <0x40676db0 + 0x0004f> in <filename unknown>:0    at Microsoft.CodeAnalysis.CodeFixes.CodeFixContext..ctor (Microsoft.CodeAnalysis.Document document, TextSpan span, ImmutableArray`1 diagnostics, System.Action`2 registerCodeFix, CancellationToken cancellationToken) <0x40676d60 + 0x0003b> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetCodeFixContext>d__9.MoveNext () <0x40675fa0 + 0x007eb> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x40677db0 + 0x0001f> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetActions>d__7.MoveNext () <0x40672430 + 0x0061e> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at OmniSharp.Api.V2.CodeActionController+<GetCodeActions>d__5.MoveNext () <0x40671b60 + 0x00166> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<CastToObject>d__8`1[T].MoveNext () <0x4039f2f0 + 0x0019b> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<ExecuteAsync>d__3.MoveNext () <0x40356dc0 + 0x0030b> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.ControllerActionExecutor+<ExecuteAsync>d__2.MoveNext () <0x40356510 + 0x0018a> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.ControllerActionInvoker+<InvokeActionAsync>d__7.MoveNext () <0x40355510 + 0x001da> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fd6d13ff8d0 + 0x00017> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeActionFilterAsync>d__41.MoveNext () <0x403520e0 + 0x00cf4> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Core.FilterActionInvoker+<InvokeAsync>d__32.MoveNext () <0x4032b510 + 0x0082d> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.MvcRouteHandler+<InvokeActionAsync>d__3.MoveNext () <0x403222f0 + 0x0036c> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.MvcRouteHandler+<RouteAsync>d__2.MoveNext () <0x4031a000 + 0x006f0> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Routing.Template.TemplateRoute+<RouteAsync>d__25.MoveNext () <0x40317fe0 + 0x007c8> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute+<RouteAsync>d__10.MoveNext () <0x403174a0 + 0x003d5> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Routing.RouteCollection+<RouteAsync>d__10.MoveNext () <0x403163a0 + 0x003b7> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Builder.RouterMiddleware+<Invoke>d__4.MoveNext () <0x403153b0 + 0x00311> in <filename unknown>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fd6d14016d0 + 0x00029> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fd6d13ff6b0 + 0x000a7> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fd6d13ff630 + 0x0006b> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fd6d13ff5e0 + 0x0003a> in <filename unknown>:0    at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fd6d13ff5c0 + 0x00012> in <filename unknown>:0    at Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware+<Invoke>d__4.MoveNext () <0x40314110 + 0x003d6> in <filename unknown>:0  [INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 404 2ms ```
1875|@stkb yeah the zoom action is only going up and down by an increment of 1. fair request.
1876|@fouckybzh is this project somewhere on github for me to play with?
1877|"I cannot reproduce from the command line (tried ""code C:"" and ""code C:\"") so I wonder if this is something with the context menu entry we provide (""Open with Code"").  @acoshift I do not even have a ""Open with Code"" in the context menu of a root drive. How did you trigger it?"
1878|@bpasero It's an option in the installer.
1879|@weinand The paths don't matter if the original sources are inlined in the sourcemaps. For `vscode/out` we don't inline them and the paths are correct. For all other `vscode/out-*` directories we always inline the sources.  No one really looked into enabling sourcemaps in extensions, I think. Someone should just dig in there and make sure that either (1) we inline the sources or (2) the paths are correct, just like in `vscode/out`.
1880|@joaomoreno I fixed those but I see many more in other places, including the tree itself:  ![image](https://cloud.githubusercontent.com/assets/900690/11423584/f310c070-9445-11e5-84f4-4bb47b02e0d4.png)
1881|This issue was moved to OmniSharp/omnisharp-roslyn#345
1882|Ok, thanks @jrieken :)
1883|It's a duplicate of OmniSharp/omnisharp-roslyn#345
1884|Please provide details steps include a code sample so that we can understand and reproduce
1885|Wow, first time I hear about this, it's very interesting! [Found this](https://github.com/atom/atom/issues/4650). I'd label this one `upstream`.
1886|![omglob](http://vignette1.wikia.nocookie.net/totaldramaisland/images/a/a0/Oh_my_Glob.gif/revision/latest?cb=20130302230724)
1887|We use the _npm way_ in our build scripts, btw.
1888|"``` public class AvaContext: DbContext     {         public DbSet<Place> Places { get; set; }         public DbSet<Location> Locations { get; set; }          protected override void OnModelCreating(ModelBuilder modelBuilder)         {             base.OnModelCreating(modelBuilder);          }         protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)         {             var appEnv = CallContextServiceLocator.Locator.ServiceProvider                             .GetRequiredService<IApplicationEnvironment>();             optionsBuilder.UseSqlite($@""Data Source={appEnv.ApplicationBasePath}/../apiava/avaDB.db"");         }     } ```  using EntityFramework 7 i created this context , for adding db connection query string `OnConfiguring` method should be overriden and in vscode intelisense not seggesting that or `OnModelCreating`"
1889|This bug makes VS Code completely unusable for ES6 development since the whole editor is obfuscated with red underlines.  I sometimes manage to get it resolved by editing jsconfig.json (add whitespace, save) but then again, only sometimes.  Sounds quite critical to me?
1890|https://github.com/fouckybzh/test-watch.git  To run the task :  ``` > npm install > gulp ```
1891|Argh forgot that I can not have a path in an error due to privacy issues. Leaving this closed until it happens again since this error currently does not give me enought space to do something
1892|Same here with a scandinavian keyboard. The key combo is `Cmd+Shift+7` which is essentially `Cmd+/`.
1893|@joaomoreno inlining sources (1) doesn't make sense for debugging extensions in the vscode workspace because inlined source is always readonly and has no relation to the actual source we have in the workspace. Inlined source makes sense for our distro if the sourcemaps come from a server and we reference the sourcemaps from our generated source through urls.
1894|@MasoodRezazadeh Do I understand correctly that this is a feature request for IntelliSense helping you to implement a method?  Like so   ``` public class AvaContext: DbContext     {         public DbSet<Place> Places { get; set; }         public DbSet<Location> Locations { get; set; }          protected override void OnModelCreating(ModelBuilder modelBuilder)         {             base.OnModelCreating(modelBuilder);          }         OnCon<IntelliSense> -> Propose to override?     } ```
1895|Everyone is invited to write an extension for that.
1896|Thanks will have a look!
1897|@bpasero  But the regression in start-up time was in the renderer side, (on each window open), so I don't think logging from the main process would have helped discover it sooner. Logging the startup time of the main process would also be useful.
1898|@alexandrudima sorry I was not clear: yes, we must log all the time it takes until the first workbench window is up and running. what I meant is that this logging code should live on the main side and not renderer side because only main side knows when the first window is opening!
1899|Same here! After update.
1900|Happens when no folder is open
